plugins {
    id 'com.android.application'
}

android {
    namespace 'com.m3u8.extractor'
    compileSdk 35

    defaultConfig {
        applicationId "com.m3u8.extractor"
        minSdk 23
        targetSdk 35

        versionCode 1
        versionName "1.0"
    }

    // 你的实际目录叫 mian，不是 main
    sourceSets {
        main {
            manifest.srcFile 'src/mian/AndroidManifest.xml'
            java.srcDirs = ['src/mian/java']
            res.srcDirs = ['src/mian/res']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
